### ISSUE TITLE
SPIGOT 1.8 Issues

### ISSUE THREAD

**Issue by d00ba** [tehbeard/BeardStat#57]
Issues running plugin on Minecraft 1.8.1
Running: SPIGOT 1.8
Running: BeardStat build #159 on CI
Errors on both sqlite and mysql 

Full server log: http://pastebin.com/gRHjBHb7
Error on player join: http://pastebin.com/hDuHHBKw
Error thrown on /stats command: http://pastebin.com/RU7v7JA7
Error on server start with MYSQL instead of sqlite: http://pastebin.com/hPkb3u5Y

**Comment by d00ba** [comment]
Build #163

- Plugin is now operating as expected in sqlite mode
- cannot launch server in mysql mode still - http://pastebin.com/pENV3nLd

config is as follows:-

stats:
  configversion: 6
  database:
    sql_db_version: 7
    type: mysql
    host: localhost
    username: 19170
    password: pass123
    database: 19170
    prefix: bdstats
    port: 3306
    backups: true
    uuidUpdate: true

**Comment by tehbeard** [comment]
hmm, try wrapping the username and database in "'s ` username: "19170" ` , could be yaml isn't liking a numerics only string.

**Comment by tehbeard** [comment]
http://ci.escapecraft.com/job/BeardStat/164/ has a fix to ensure this shouldn't happen hopefully.

**Comment by d00ba** [comment]
Plugin broken since build 164 upto build 167 - NullPointerException onstart 

http://pastebin.com/bbAZQZGc

**Comment by tehbeard** [comment]
Ok, reverted the commit for 163 and added some code to show the errors.

**Comment by d00ba** [comment]
More thorough testing shows mysql mode is still broken. Server and plugin launch OK but errors occur on player join or running commands - http://pastebin.com/yNULHiSx

Note sqlite mode works as expected.

**Comment by tehbeard** [comment]
Hmm. Does the player have any data in the database already?

**Comment by tehbeard** [comment]
found the bug, missed checking a certain flag, fixed in 9d5a12c03ef8ee90ca4a6f5c13b544f746b5cb5d

http://ci.escapecraft.com/job/BeardStat/169/
